name: 'Deploy Infra in Dev [Resource Based]'

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
    paths:
      - "infrastructure/resource-based/**"
      - '.github/workflows/resource.infra.dev.deploy.yml'

  push:
    branches:
      - 'main'
      - 'feature/*'
    paths:
      - "infrastructure/resource-based/**"
      - '.github/workflows/resource.infra.dev.deploy.yml'

env:
  RG_NAME: "rgazewglobalazuredemo"

jobs:
  validate:
    name: 'Lint and Validate'
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' 
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.3.0

    - name: Az CLI Login via OIDC
      uses: azure/login@v1
      with:
        client-id: "721121da-9956-4f2d-a308-055b22ee07e0"
        tenant-id: "8a67a398-d847-467d-8784-862a887f1386"
        subscription-id: "1c190342-9d6f-48cb-b208-86ca9725c9a6"

    - name: Bicep Lint
      uses: Azure/cli@v1
      with:
        inlineScript: |
          cd ${{ github.workspace }}/infrastructure/resource-based/resources
          az bicep build --file main.bicep

    - name: Bicep Validate
      uses: Azure/cli@v1
      with:
        inlineScript: |
          cd ${{ github.workspace }}/infrastructure/resource-based
          az deployment group validate \
            --resource-group ${{ env.RG_NAME }} \
            --name validate-${{ github.run_id }} \
            --template-file ./resources/main.bicep \
            --parameters ./environments/dev.parameters.json

  pr-check:
    name: 'Automated PR Check'
    if: github.event_name == 'pull_request' 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.3.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"721121da-9956-4f2d-a308-055b22ee07e0","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"1c190342-9d6f-48cb-b208-86ca9725c9a6","tenantId":"8a67a398-d847-467d-8784-862a887f1386"}'

    - name: "What-If"
      uses: Azure/cli@v1
      with:
        inlineScript: |
          cd ${{ github.workspace }}/infrastructure/resource-based
          az deployment group what-if \
            --resource-group ${{ env.RG_NAME }} \
            --name whatif-${{ github.run_id }} \
            --template-file ./resources/main.bicep \
            --parameters ./environments/dev.parameters.json > whatif

    - name: PrePare Output
      id: whatif-output
      run: |
        cd ${{ github.workspace }}/infrastructure/resource-based
        WHATIF=$(cat whatif)
        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Whatif Output" >> $GITHUB_OUTPUT
        echo "<details><summary>Click here to see the result</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "$WHATIF" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Post to the Step Summary
      env:
        SUMMARY_OUTPUT: ${{ steps.whatif-output.outputs.summary }}
      run: |
        echo "$SUMMARY_OUTPUT" >> $GITHUB_STEP_SUMMARY

    - name: Update PR Comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      env:
        SUMMARY_OUTPUT: "${{ steps.whatif-output.outputs.summary }}"
      with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY_OUTPUT}`;
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
            })


  what-if:
    name: 'What-If'
    if: github.event_name != 'pull_request' 
    needs: [validate]
    runs-on: ubuntu-latest
    environment: pull_request
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.3.0

    - name: Az CLI Login via OIDC
      uses: azure/login@v1
      with:
        client-id: "721121da-9956-4f2d-a308-055b22ee07e0"
        tenant-id: "8a67a398-d847-467d-8784-862a887f1386"
        subscription-id: "1c190342-9d6f-48cb-b208-86ca9725c9a6"

    - name: "What-If"
      uses: Azure/cli@v1
      with:
        inlineScript: |
          cd ${{ github.workspace }}/infrastructure/resource-based
          az deployment group what-if \
            --resource-group ${{ env.RG_NAME }} \
            --name whatif-${{ github.run_id }} \
            --template-file ./resources/main.bicep \
            --parameters ./environments/dev.parameters.json > whatif

    - name: PrePare Output
      id: whatif-output
      run: |
        cd ${{ github.workspace }}/infrastructure/resource-based
        WHATIF=$(cat whatif)
        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Whatif Output" >> $GITHUB_OUTPUT
        echo "<details><summary>Click here to see the result</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "$WHATIF" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Post to the Step Summary
      env:
        SUMMARY_OUTPUT: ${{ steps.whatif-output.outputs.summary }}
      run: |
        echo "$SUMMARY_OUTPUT" >> $GITHUB_STEP_SUMMARY

  deploy:
    name: 'Deploy Infra'
    if: |
      github.event_name != 'pull_request' &&
      github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    environment: dev
    needs: [what-if]
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Az CLI Login via OIDC
      uses: azure/login@v1
      with:
        client-id: "721121da-9956-4f2d-a308-055b22ee07e0"
        tenant-id: "8a67a398-d847-467d-8784-862a887f1386"
        subscription-id: "1c190342-9d6f-48cb-b208-86ca9725c9a6"

    - name: "Infra Deployment"
      uses: Azure/cli@v1
      with:
        inlineScript: |
          cd ${{ github.workspace }}/infrastructure/resource-based
          az deployment group create \
            --resource-group ${{ env.RG_NAME }} \
            --name validate-${{ github.run_id }} \
            --template-file ./resources/main.bicep \
            --parameters ./environments/dev.parameters.json
